bitnum=8;
graylevel=2^bitnum;
img=imread('..\..\images\lenna.tif');

%%Zonal mask.
figure(1);
suptitle('Using Zonal mask');
subplot(1,3,1);
imshow(img,[0 graylevel-1]);
xlabel('original image');drawnow;
resData=DCTCompress(img,'Zonal');
resImg=uint16(resData);
subplot(1,3,2);
imshow(resImg,[0 graylevel-1]);
xlabel('reconstructed image');drawnow;
diffimg=double(img)-resData;
minval=min(diffimg(:));maxval=max(diffimg(:));
diffimg=(diffimg-minval)/(maxval-minval);
subplot(1,3,3);
imshow(diffimg);
xlabel('difference image');drawnow;

%%Threshold mask.
resData=DCTCompress(img,'Threshold',1);
resImg=uint16(resData);
figure(2);
suptitle('reconstructed images using threshold mask(with normalization array)');
subplot(2,3,1);
imshow(resImg,[0 graylevel-1]);
xlabel({'$$\mathbf{Z}$$'},'Interpreter','latex');drawnow;
diffimg=double(img)-resData;
minval=min(diffimg(:));maxval=max(diffimg(:));
diffimg=(diffimg-minval)/(maxval-minval);
figure(3);
suptitle('difference images using threshold mask(with normalization array)');
subplot(2,3,1);
imshow(diffimg);
xlabel({'$$\mathbf{Z}$$'},'Interpreter','latex');drawnow;

resData=DCTCompress(img,'Threshold',2);
resImg=uint16(resData);
figure(2);
subplot(2,3,2);
imshow(resImg,[0 graylevel-1]);
xlabel({'$$2\mathbf{Z}$$'},'Interpreter','latex');drawnow;
diffimg=double(img)-resData;
minval=min(diffimg(:));maxval=max(diffimg(:));
diffimg=(diffimg-minval)/(maxval-minval);
figure(3);
subplot(2,3,2);
imshow(diffimg);
xlabel({'$$2\mathbf{Z}$$'},'Interpreter','latex');drawnow;

resData=DCTCompress(img,'Threshold',4);
resImg=uint16(resData);
figure(2);
subplot(2,3,3);
imshow(resImg,[0 graylevel-1]);
xlabel({'$$4\mathbf{Z}$$'},'Interpreter','latex');drawnow;
diffimg=double(img)-resData;
minval=min(diffimg(:));maxval=max(diffimg(:));
diffimg=(diffimg-minval)/(maxval-minval);
figure(3);
subplot(2,3,3);
imshow(diffimg);
xlabel({'$$4\mathbf{Z}$$'},'Interpreter','latex');drawnow;

resData=DCTCompress(img,'Threshold',8);
resImg=uint16(resData);
figure(2);
subplot(2,3,4);
imshow(resImg,[0 graylevel-1]);
xlabel({'$$8\mathbf{Z}$$'},'Interpreter','latex');drawnow;
diffimg=double(img)-resData;
minval=min(diffimg(:));maxval=max(diffimg(:));
diffimg=(diffimg-minval)/(maxval-minval);
figure(3);
subplot(2,3,4);
imshow(diffimg);
xlabel({'$$8\mathbf{Z}$$'},'Interpreter','latex');drawnow;

resData=DCTCompress(img,'Threshold',16);
resImg=uint16(resData);
figure(2);
subplot(2,3,5);
imshow(resImg,[0 graylevel-1]);
xlabel({'$$16\mathbf{Z}$$'},'Interpreter','latex');drawnow;
diffimg=double(img)-resData;
minval=min(diffimg(:));maxval=max(diffimg(:));
diffimg=(diffimg-minval)/(maxval-minval);
figure(3);
subplot(2,3,5);
imshow(diffimg);
xlabel({'$$16\mathbf{Z}$$'},'Interpreter','latex');drawnow;

resData=DCTCompress(img,'Threshold',32);
resImg=uint16(resData);
figure(2);
subplot(2,3,6);
imshow(resImg,[0 graylevel-1]);
xlabel({'$$32\mathbf{Z}$$'},'Interpreter','latex');drawnow;
diffimg=double(img)-resData;
minval=min(diffimg(:));maxval=max(diffimg(:));
diffimg=(diffimg-minval)/(maxval-minval);
figure(3);
subplot(2,3,6);
imshow(diffimg);
xlabel({'$$32\mathbf{Z}$$'},'Interpreter','latex');drawnow;

[resData,dwtRes]=DWTCompress(img,'Haar',3,1.5);
resImg=uint16(resData);
figure(4);
suptitle('DWT with Haar wavelet');
subplot(1,2,1);
imshow(dwtRes);
xlabel('wavelet transform');drawnow;
subplot(1,2,2);
imshow(resImg,[0 graylevel-1]);
xlabel('reconstructed image');drawnow;

[resData,dwtRes]=DWTCompress(img,'Daubechies',3,1.5);
resImg=uint16(resData);
figure(5);
suptitle('DWT with Daubechies wavelet(8-tap)');
subplot(1,2,1);
imshow(dwtRes);
xlabel('wavelet transform');drawnow;
subplot(1,2,2);
imshow(resImg,[0 graylevel-1]);
xlabel('reconstructed image');drawnow;

[resData,dwtRes]=DWTCompress(img,'Symlet',3,1.5);
resImg=uint16(resData);
figure(6);
suptitle('DWT with Symlet wavelet(8-tap)');
subplot(1,2,1);
imshow(dwtRes);
xlabel('wavelet transform');drawnow;
subplot(1,2,2);
imshow(resImg,[0 graylevel-1]);
xlabel('reconstructed image');drawnow;

[resData,dwtRes]=DWTCompress(img,'CDF',3,1.5);
resImg=uint16(resData);
figure(7);
suptitle('DWT with the biorthogonal Cohen-Daubechies-Feauveau wavelet');
subplot(1,2,1);
imshow(dwtRes);
xlabel('wavelet transform');drawnow;
subplot(1,2,2);
imshow(resImg,[0 graylevel-1]);
xlabel('reconstructed image');drawnow;