bitnum=8;
graylevel=2^bitnum;

img=imread('../../images/characters_test_pattern.tif');

paras=[10;30;60;160;460];
type='ILPF';
%type='IHPF';
titletext=type;

%paras=[10 2;30 2;60 2;160 2;460 2];
%type='BLPF';
%type='BHPF';
%titletext=strcat(type,'(n=2)');

%paras=[10;30;60;160;460];
%type='GLPF';
%type='GHPF';
%titletext=type;

[res,spec,spec2]=dipFreqFilter(img,type,paras(1,:),bitnum,false);
figure;
suptitle(titletext);
subplot(4,3,1);
imshow(img,[0 graylevel-1]);
xlabel('origin image');
subplot(4,3,7);
showSpectrum(spec);
xlabel('Fourier spectrum of origin image');drawnow;
subplot(4,3,2);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(1,1))));
subplot(4,3,8);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(1,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(2,:),bitnum,false);
subplot(4,3,3);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(2,1))));
subplot(4,3,9);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(2,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(3,:),bitnum,false);
subplot(4,3,4);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(3,1))));
subplot(4,3,10);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(3,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(4,:),bitnum,false);
subplot(4,3,5);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(4,1))));
subplot(4,3,11);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(4,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(5,:),bitnum,false);
subplot(4,3,6);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(5,1))));
subplot(4,3,12);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(5,1))));drawnow;

paras=[10;30;60;160;460];
%type='ILPF';
type='IHPF';
titletext=type;

%paras=[10 2;30 2;60 2;160 2;460 2];
%type='BLPF';
%type='BHPF';
%titletext=strcat(type,'(n=2)');

%paras=[10;30;60;160;460];
%type='GLPF';
%type='GHPF';
%titletext=type;

[res,spec,spec2]=dipFreqFilter(img,type,paras(1,:),bitnum,false);
figure;
suptitle(titletext);
subplot(4,3,1);
imshow(img,[0 graylevel-1]);
xlabel('origin image');
subplot(4,3,7);
showSpectrum(spec);
xlabel('Fourier spectrum of origin image');drawnow;
subplot(4,3,2);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(1,1))));
subplot(4,3,8);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(1,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(2,:),bitnum,false);
subplot(4,3,3);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(2,1))));
subplot(4,3,9);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(2,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(3,:),bitnum,false);
subplot(4,3,4);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(3,1))));
subplot(4,3,10);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(3,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(4,:),bitnum,false);
subplot(4,3,5);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(4,1))));
subplot(4,3,11);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(4,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(5,:),bitnum,false);
subplot(4,3,6);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(5,1))));
subplot(4,3,12);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(5,1))));drawnow;

%paras=[10;30;60;160;460];
%type='ILPF';
%type='IHPF';
%titletext=type;

paras=[10 2;30 2;60 2;160 2;460 2];
type='BLPF';
%type='BHPF';
titletext=strcat(type,'(n=2)');

%paras=[10;30;60;160;460];
%type='GLPF';
%type='GHPF';
%titletext=type;

[res,spec,spec2]=dipFreqFilter(img,type,paras(1,:),bitnum,false);
figure;
suptitle(titletext);
subplot(4,3,1);
imshow(img,[0 graylevel-1]);
xlabel('origin image');
subplot(4,3,7);
showSpectrum(spec);
xlabel('Fourier spectrum of origin image');drawnow;
subplot(4,3,2);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(1,1))));
subplot(4,3,8);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(1,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(2,:),bitnum,false);
subplot(4,3,3);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(2,1))));
subplot(4,3,9);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(2,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(3,:),bitnum,false);
subplot(4,3,4);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(3,1))));
subplot(4,3,10);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(3,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(4,:),bitnum,false);
subplot(4,3,5);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(4,1))));
subplot(4,3,11);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(4,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(5,:),bitnum,false);
subplot(4,3,6);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(5,1))));
subplot(4,3,12);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(5,1))));drawnow;

%paras=[10;30;60;160;460];
%type='ILPF';
%type='IHPF';
%titletext=type;

paras=[10 2;30 2;60 2;160 2;460 2];
%type='BLPF';
type='BHPF';
titletext=strcat(type,'(n=2)');

%paras=[10;30;60;160;460];
%type='GLPF';
%type='GHPF';
%titletext=type;

[res,spec,spec2]=dipFreqFilter(img,type,paras(1,:),bitnum,false);
figure;
suptitle(titletext);
subplot(4,3,1);
imshow(img,[0 graylevel-1]);
xlabel('origin image');
subplot(4,3,7);
showSpectrum(spec);
xlabel('Fourier spectrum of origin image');drawnow;
subplot(4,3,2);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(1,1))));
subplot(4,3,8);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(1,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(2,:),bitnum,false);
subplot(4,3,3);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(2,1))));
subplot(4,3,9);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(2,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(3,:),bitnum,false);
subplot(4,3,4);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(3,1))));
subplot(4,3,10);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(3,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(4,:),bitnum,false);
subplot(4,3,5);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(4,1))));
subplot(4,3,11);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(4,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(5,:),bitnum,false);
subplot(4,3,6);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(5,1))));
subplot(4,3,12);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(5,1))));drawnow;

%paras=[10;30;60;160;460];
%type='ILPF';
%type='IHPF';
%titletext=type;

%paras=[10 2;30 2;60 2;160 2;460 2];
%type='BLPF';
%type='BHPF';
%titletext=strcat(type,'(n=2)');

paras=[10;30;60;160;460];
type='GLPF';
%type='GHPF';
titletext=type;

[res,spec,spec2]=dipFreqFilter(img,type,paras(1,:),bitnum,false);
figure;
suptitle(titletext);
subplot(4,3,1);
imshow(img,[0 graylevel-1]);
xlabel('origin image');
subplot(4,3,7);
showSpectrum(spec);
xlabel('Fourier spectrum of origin image');drawnow;
subplot(4,3,2);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(1,1))));
subplot(4,3,8);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(1,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(2,:),bitnum,false);
subplot(4,3,3);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(2,1))));
subplot(4,3,9);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(2,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(3,:),bitnum,false);
subplot(4,3,4);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(3,1))));
subplot(4,3,10);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(3,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(4,:),bitnum,false);
subplot(4,3,5);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(4,1))));
subplot(4,3,11);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(4,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(5,:),bitnum,false);
subplot(4,3,6);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(5,1))));
subplot(4,3,12);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(5,1))));drawnow;

%paras=[10;30;60;160;460];
%type='ILPF';
%type='IHPF';
%titletext=type;

%paras=[10 2;30 2;60 2;160 2;460 2];
%type='BLPF';
%type='BHPF';
%titletext=strcat(type,'(n=2)');

paras=[10;30;60;160;460];
%type='GLPF';
type='GHPF';
titletext=type;

[res,spec,spec2]=dipFreqFilter(img,type,paras(1,:),bitnum,false);
figure;
suptitle(titletext);
subplot(4,3,1);
imshow(img,[0 graylevel-1]);
xlabel('origin image');
subplot(4,3,7);
showSpectrum(spec);
xlabel('Fourier spectrum of origin image');drawnow;
subplot(4,3,2);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(1,1))));
subplot(4,3,8);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(1,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(2,:),bitnum,false);
subplot(4,3,3);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(2,1))));
subplot(4,3,9);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(2,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(3,:),bitnum,false);
subplot(4,3,4);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(3,1))));
subplot(4,3,10);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(3,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(4,:),bitnum,false);
subplot(4,3,5);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(4,1))));
subplot(4,3,11);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(4,1))));drawnow;
[res,spec,spec2]=dipFreqFilter(img,type,paras(5,:),bitnum,false);
subplot(4,3,6);
imshow(uint16(res),[0 graylevel-1]);
xlabel(strcat('D_0=',num2str(paras(5,1))));
subplot(4,3,12);
showSpectrum(spec2);
xlabel(strcat('D_0=',num2str(paras(5,1))));drawnow;